# -*- mode: python ; coding: utf-8 -*-
# Sistema de Gestion para Librerias - PyInstaller spec

added_files = [
    ('app.html', '.'),
    ('assets',   'assets'),
    ('data',     'data'),
]

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=added_files,
    hiddenimports=[
        # Modulos del programa
        'sqlite3',
        'hashlib',
        'base64',
        'webbrowser',
        'threading',
        'json',
        'mimetypes',
        # http.server y dependencias
        'http',
        'http.server',
        'http.client',
        'urllib',
        'urllib.parse',
        'urllib.request',
        # email: requerido por http.server
        'email',
        'email.parser',
        'email.message',
        'email.feedparser',
        'email.errors',
        'email.header',
        'email.charset',
        'email.encoders',
        'email.utils',
        # html: usado por http.server
        'html',
        'html.parser',
        # System tray
        'pystray',
        'pystray._win32',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        # Pillow internals que PyInstaller suele perder
        'PIL._imaging',
        'PIL.PngImagePlugin',
        'PIL.JpegImagePlugin',
        'PIL.BmpImagePlugin',
        'PIL.IcoImagePlugin',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'unittest',
        'xmlrpc',
        'pydoc',
        'doctest',
        'difflib',
        'ftplib',
        'imaplib',
        'poplib',
        'smtplib',
        'telnetlib',
        'turtledemo',
        'curses',
        'readline',
        'rlcompleter',
        'numpy',
        'pandas',
        'cv2',
        'matplotlib',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'wx',
    ],
    noarchive=False,
    optimize=1,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SistemaLibreria',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
